spring:
  application:
    name: yu-ai-agent
  profiles:
    active: local
  ai:
    mcp:
      client:
#        stdio:
#          servers-configuration: classpath:mcp-servers.json
        sse:
          connections:
            server1:
              url: http://localhost:8127

server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.lcz.yuaiagent.controller
# knife4j增强配置
knife4j:
  enable: true
  setting:
    language:
# 开启工具debug模式
logging:
  level:
    org.springframework.ai: DEBUG

